AWSTemplateFormatVersion: 2010-09-09
Description: Deploying infra from circle CI 
Resources:
  SecurityGroupEC2:
      Type: AWS::EC2::SecurityGroup
      Properties: 
          VpcId: vpc-068e48044ec1a3bda 
          GroupDescription: SG from CICD for web server www
          SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0  
          Tags: 
          - Key: Name
            Value: SG from CICD for web server www
  
  EC2:
      Type: AWS::EC2::Instance
      Properties: 
          AvailabilityZone: !Select [0, !GetAZs '']
          ImageId: ami-0ee8244746ec5d6d4 #ubuntu
          InstanceType: t2.micro
          KeyName: kp-cicd-project2 
          SecurityGroupIds:  
          - !Ref SecurityGroupEC2 
          SubnetId: subnet-0b78a6a22feaf7180
          Tags: 
          - Key: Name
            Value: CiCd-Ansible-Ubuntu