AWSTemplateFormatVersion: 2010-09-09
Description: deploy infra via circle CI 
Resources:
  # EC2Instance:
  #   Type: 'AWS::EC2::Instance'
  #   Properties:
  #     SecurityGroups:
  #       - !Ref InstanceSecurityGroup
  #     # Change this, as applicable to you      
  #     KeyName: kp-na-2605
  #     # Change this, as applicable to you
  #     # You may need to find out what instance types are available in your region - use https://cloud-images.ubuntu.com/locator/ec2/
  #     ImageId: 'ami-0ee8244746ec5d6d4' 
  #     InstanceType: t2.micro


   ##

  SecurityGroupEC2:
      Type: AWS::EC2::SecurityGroup
      Properties: 
          VpcId: vpc-068e48044ec1a3bda 
          GroupDescription: SG from CICD for web server www
          SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0 #176.248.19.111/32 # my ip address  
          Tags: 
          - Key: Name
            Value: SG from CICD for web server www
  
  EC2:
      Type: AWS::EC2::Instance
      Properties: 
          AvailabilityZone: !Select [0, !GetAZs '']
          ImageId: ami-0ee8244746ec5d6d4 #ubuntu
          InstanceType: t2.micro
          KeyName: kp-cicd-project2 
          SecurityGroupIds:  
          - !Ref SecurityGroupEC2 
          SubnetId: subnet-0b78a6a22feaf7180
          Tags: 
          - Key: Name
            Value: CiCd-Ansible-Ubuntu